### ISSUE TITLE
Cannot add RSS and News Slider on the same page

### ISSUE THREAD

**Issue by joancloete** [OlivierCC/spfx-40-fantastics#8]
I am trying to add 2 web parts on the same Classic page, but only one displays at a time. I am able to add and configure both, but only one displays after saving the page.

![image](https://cloud.githubusercontent.com/assets/13382195/23545464/1874976c-0004-11e7-83d5-2d6df7dfd4c5.png)

**Comment by OlivierCC** [comment]
Thanks @joancloete for your feedback. I will investigate it.

**Comment by OlivierCC** [comment]
OK Thanks @joancloete. I didn't identify a workaround, but the issue is known. I will fix it for the next release. Thanks for this report.

**Comment by joancloete** [comment]
Hi, thank you for the feedback! I have tested it on the modern pages as well, hoping to get more than one web part on a page. I received an error message this time on the news web part: 

"Unite Gallery Error: You have some jquery.js library include that comes after the gallery files js include.
This include eliminates the gallery libraries, and make it not work.

To fix it you can:
    1. In the Gallery Settings -> Troubleshooting set option: Put JS Includes To Body option to true.
    2. Find the double jquery.js include and remove it."

**Comment by OlivierCC** [comment]
Hi @joancloete. Yes you're right, the problem comes from the fact that the jQuery library is loaded several times. Webparts with a jQuery plugin are blocked because jQuery is reset. I corrected the problem in version 1.0.2 which is available for download. The fix is a little dirty, but I worked to a cleaner version in the future. Thanks again for this bug report.

**Comment by joancloete** [comment]
Thank you very much! I am now able to add more than one web part on the modern and classic pages.
